### ISSUE TITLE
Can't run ios - error code 65

### ISSUE THREAD

**Issue by idanlevi1** [Jobeso/react-native-story-share#14]
When i tried version 0.2.0 its work for me only in Android,
in ios i got :
```
info   "_swift_unknownObjectRelease", referenced from:

info       RNStoryShare.RNStoryShare.share(_: __C.NSDictionary, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libRNStoryShare.a(RNStoryShare-5898797e35bc08a442bbd70b6ac41c79923a55e5e3af2d3e4ed70530ae898915.o)

info       reabstraction thunk helper from @callee_unowned @convention(block) (@unowned Swift.AnyObject?) -> () to @escaping @callee_guaranteed (@in_guaranteed Any?) -> () in libRNStoryShare.a(RNStoryShare-5898797e35bc08a442bbd70b6ac41c79923a55e5e3af2d3e4ed70530ae898915.o)

info   "_swift_updateClassMetadata2", referenced from:

info       type metadata completion function for RNStoryShare.RNStoryShare in libRNStoryShare.a(RNStoryShare-5898797e35bc08a442bbd70b6ac41c79923a55e5e3af2d3e4ed70530ae898915.o)

info   "_swift_willThrow", referenced from:

info       RNStoryShare.RNStoryShare.share(_: __C.NSDictionary, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libRNStoryShare.a(RNStoryShare-5898797e35bc08a442bbd70b6ac41c79923a55e5e3af2d3e4ed70530ae898915.o)

info       RNStoryShare.RNStoryShare.shareToInstagram(_: __C.NSData, stickerData: __C.NSData?, attributionLink: Swift.String, resolve: (Any?) -> (), reject: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libRNStoryShare.a(RNStoryShare-5898797e35bc08a442bbd70b6ac41c79923a55e5e3af2d3e4ed70530ae898915.o)

info ld: symbol(s) not found for architecture x86_64

info clang: error: linker command failed with exit code 1 (use -v to see invocation)

info 

error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening hangmeout.xcworkspace

** BUILD FAILED **


The following build commands failed:
        Ld /Users/idanlevi/Documents/idan/hangmeout/ios/build/hangmeout/Build/Products/Debug-iphonesimulator/hangmeout.app/hangmeout normal x86_64
(1 failure)
. Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
```

I also try the latest version 0.4.0, but it's not working...
maybe i didn't installation well,
i work with react native 59.8 and cocoapods
i try to add   `# pod 'RNStoryShare', :path => '../node_modules/react-native-story-share/ios'`
to `Podfile` , it looks like install RNStoryShare...
I'm also linking in `xcode`
*i work with `yarn`
maybe i miss something with snapchat
I don't understand why i need it if i want work only with `Instagram` ? and how i . get snapchat SDK ?

someone can explain to me what the installation steps more slowly?

**Comment by Jobeso** [comment]
This probably has something to do because you install it via cocoa pods. You might need to activate `use_framworks!` in your Podfile in order to make this work. On another note, it could also have something to do with the linking flags, maybe [this](https://stackoverflow.com/questions/38199190/undefined-symbols-for-architecture-x86-64-afnetworking-with-cocoapods) helps you to find the problem. Otherwise, you can also use one of the forks of this library who removed snapchat support.
